# Generated by Django 5.1.7 on 2025-03-28 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_title",
                    models.CharField(
                        blank=True, null=True, verbose_name="記事タイトル"
                    ),
                ),
                (
                    "article_url",
                    models.URLField(blank=True, null=True, verbose_name="記事URL"),
                ),
                (
                    "article_img_url",
                    models.URLField(blank=True, null=True, verbose_name="記事画像URL"),
                ),
                ("memo", models.CharField(blank=True, null=True, verbose_name="メモ")),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="記事公開日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "article",
            },
        ),
    ]
