# Generated by Django 5.1.7 on 2025-03-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="published_at",
            field=models.DateField(blank=True, null=True, verbose_name="記事公開日時"),
        ),
    ]
