# Generated by Django 5.1.7 on 2025-03-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0002_alter_article_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_url",
            field=models.URLField(
                blank=True, null=True, unique=True, verbose_name="記事URL"
            ),
        ),
    ]
