# Generated by Django 5.1.7 on 2025-03-29 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0003_alter_article_article_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_url",
            field=models.URLField(blank=True, null=True, verbose_name="記事URL"),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                fields=("user", "article_url"), name="unique_user_article_url"
            ),
        ),
    ]
